salle_tp_test1: 
    path:  /test1 
    defaults: { _controller: SalleTpBundle:Essai:test1 }    
    
salle_tp_test2: 
    path:  /test2
    defaults: { _controller: SalleTpBundle:Essai:test2 }  
    
salle_tp_test3: 
    path:  /test3
    defaults: { _controller: SalleTpBundle:Essai:test3 }   
    
salle_tp_test4: 
    path:  /test4 
    defaults: { _controller: SalleTpBundle:Essai:test4 }    
    
salle_tp_test5: 
    path:  /test5
    defaults: { _controller: SalleTpBundle:Essai:test5 }  
    
salle_tp_test6: 
    path:  /test6
    defaults: { _controller: SalleTpBundle:Essai:test6 }  
    
salle_tp_test7: 
    path:  /test7
    defaults: { _controller: SalleTpBundle:Essai:test7 }
    
salle_tp_test8: 
    path:  /test8
    defaults: { _controller: SalleTpBundle:Essai:test8 }    
    
salle_tp_test8bis: 
    path:  /test8bis
    defaults: { _controller: SalleTpBundle:Essai:test8bis }    
    
salle_tp_test9: 
    path:  /test9
    defaults: { _controller: SalleTpBundle:Essai:test9 }
    
salle_tp_test10: 
    path:  /test10 
    defaults: { _controller: SalleTpBundle:Essai:test10 }    
    
salle_tp_test11: 
    path:  /test11
    defaults: { _controller: SalleTpBundle:Essai:test11 }    
    
salle_tp_test12: 
    path:  /test12
    defaults: { _controller: SalleTpBundle:Essai:test12 }    
    
salle_tp_test13: 
    path:  /test13
    defaults: { _controller: SalleTpBundle:Essai:test13 } 
    
salle_tp_test14: 
    path:  /test14
    defaults: { _controller: SalleTpBundle:Essai:test14 }    
        
salle_tp_test15: 
    path:  /test15
    defaults: { _controller: SalleTpBundle:Essai:test15 }    
    
salle_tp_test16: 
    path:  /test16
    defaults: { _controller: SalleTpBundle:Essai:test16 }    
        
salle_tp_test17:
    path:  /test17
    defaults: { _controller: SalleTpBundle:Essai:test17 }    
            
salle_tp_test18:
    path:  /test18
    defaults: { _controller: SalleTpBundle:Essai:test18 }    
                
salle_tp_test19:
    path:  /test19
    defaults: { _controller: SalleTpBundle:Essai:test19 }    
                
salle_tp_test20:
    path:  /test20
    defaults: { _controller: SalleTpBundle:Essai:test20 }    
                    
salle_tp_test21:
    path:  /test21
    defaults: { _controller: SalleTpBundle:Essai:test21 }    
                    
salle_tp_test22:
    path:  /test22
    defaults: { _controller: SalleTpBundle:Essai:test22 }    
                    
salle_tp_test23:
    path:  /test23
    defaults: { _controller: SalleTpBundle:Essai:test23 }    
                    
salle_tp_test24:
    path:  /test24
    defaults: { _controller: SalleTpBundle:Essai:test24 }    
                    
salle_tp_test25:
    path:  /test25
    defaults: { _controller: SalleTpBundle:Essai:test25 }    
                        
salle_tp_test26:
    path:  /test26
    defaults: { _controller: SalleTpBundle:Essai:test26 }   
    
salle_tp_test27:
    path:  /test27
    defaults: { _controller: SalleTpBundle:Essai:test27 }    
        
salle_tp_test28:
    path:  /test28
    defaults: { _controller: SalleTpBundle:Essai:test28 }    
            
salle_tp_test29:
    path:  /test29
    defaults: { _controller: SalleTpBundle:Essai:test29 }    
    
salle_tp_test30:
    path:  /test30
    defaults: { _controller: SalleTpBundle:Essai:test30 }    
                    
salle_tp_test31:
    path:  /test31
    defaults: { _controller: SalleTpBundle:Essai:test31 }    
                    
salle_tp_test32:
    path:  /test32
    defaults: { _controller: SalleTpBundle:Essai:test32 }                        
                    
salle_tp_test33:
    path:  /test33
    defaults: { _controller: SalleTpBundle:Essai:test33 }    
                                       
salle_tp_test34:
    path:  /test34
    defaults: { _controller: SalleTpBundle:Essai:test34 }    
                                            
salle_tp_test35:
    path:  /test35
    defaults: { _controller: SalleTpBundle:Essai:test35 }    
                                                          
salle_tp_test36:
    path:  /test36
    defaults: { _controller: SalleTpBundle:Essai:test36 }    
                                                                              
salle_tp_test37:
    path:  /test37
    defaults: { _controller: SalleTpBundle:Essai:test37 }    
                                                                              
salle_tp_test38:
    path:  /test38
    defaults: { _controller: SalleTpBundle:Essai:test38 }    
                                                                               
salle_tp_test39:
    path:  /test39
    defaults: { _controller: SalleTpBundle:Essai:test39 }    
                       
salle_tp_test40: 
    path:  /test40 
    defaults: { _controller: SalleTpBundle:Essai:test40 }    
                          
salle_tp_test41: 
    path:  /test41
    defaults: { _controller: SalleTpBundle:Essai:test41 }    
                              
salle_tp_test42: 
    path:  /test42
    defaults: { _controller: SalleTpBundle:Essai:test42 }    
    
salle_tp_test50: 
    path:  /test42
    defaults: { _controller: SalleTpBundle:Essai:test42 }    
    
    

