<?php

namespace ExoPetsBundle\Repository;

/**
 * MaitreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MaitreRepository extends \Doctrine\ORM\EntityRepository
{
}
